# Form implementation generated from reading ui file 'pyqtSettings.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pyqtSettings(object):
    def setupUi(self, pyqtSettings):
        pyqtSettings.setObjectName("pyqtSettings")
        pyqtSettings.resize(640, 480)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=pyqtSettings)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tableWidget = QtWidgets.QTableWidget(parent=pyqtSettings)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 601, 421))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(24)
        self.tableWidget.verticalHeader().setMinimumSectionSize(50)
        self.tableWidget.verticalHeader().setStretchLastSection(False)

        self.retranslateUi(pyqtSettings)
        self.buttonBox.accepted.connect(pyqtSettings.accept) # type: ignore
        self.buttonBox.rejected.connect(pyqtSettings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(pyqtSettings)

    def retranslateUi(self, pyqtSettings):
        _translate = QtCore.QCoreApplication.translate
        pyqtSettings.setWindowTitle(_translate("pyqtSettings", "Settings - pymd3GUI"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("pyqtSettings", "Log maximum block count"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("pyqtSettings", "usbmuxd socket"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("pyqtSettings", "socat path"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("pyqtSettings", "Type"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("pyqtSettings", "Value"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("pyqtSettings", "int"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("pyqtSettings", "4069"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("pyqtSettings", "str"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("pyqtSettings", "/var/run/usbmuxd"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("pyqtSettings", "str"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("pyqtSettings", "/opt/homebrew/bin/socat"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
